"""Shared event type constants."""

SESSION_STARTED = "session_started"
SESSION_FINISHED = "session_finished"
TASK_STARTED = "task_started"
TASK_FINISHED = "task_finished"
USER_MESSAGE = "user_message"
AGENT_MESSAGE = "agent_message"
TOOL_CALL_STARTED = "tool_call_started"
TOOL_CALL_FINISHED = "tool_call_finished"
TOOL_CALL_FAILED = "tool_call_failed"
FILE_READ = "file_read"
FILE_SEARCH = "file_search"
FILE_EDIT = "file_edit"
SKILL_LOADED = "skill_loaded"
PLUGIN_INVOKED = "plugin_invoked"
